### ISSUE TITLE
No function in folia.py to retrieve all chunks from folia document (or paragraph or sentence)

### ISSUE THREAD

**Issue by antske** [proycon/pynlpl#16]

**Comment by proycon** [comment]
Retrieving annotations of whatever type can be done using the ``select()`` method available on every folia element (see http://pynlpl.readthedocs.io/en/latest/folia.html#select-method) or the higher-order ``annotation()``/``annotations()`` methods available on most (see http://pynlpl.readthedocs.io/en/latest/folia.html#annotations).

Obtaining all chunks for the entire document can be done as follows for example:

     for chunk in doc.select(folia.Chunk):
          ...
