### ISSUE TITLE
Enable proper confusion matrix in case of a dissimilarity between goals and observations

### ISSUE THREAD

**Issue by fkunneman** [proycon/pynlpl#43]
At the moment, the confusion matrix module in evaluation.py seems to model the matrix based on the categories that are seen in the observations. It would make more sense, however, if the matrix was made based on the category set in goals. For example, in case of two categories in the goals of which only one was predicted, the matrix is currently plotted as one-by-one instead of a 2x2 matrix with one cell valued '0'.

**Comment by proycon** [comment]
Hmm, right, I currently base it only on observations.. I guess I should base it not on goals (then we might end up with the inverse problem?), but on the union of goals and observations.
