### ISSUE TITLE
Formats.Giza: IntersectionAlignment does not append the 0-0 alignment

### ISSUE THREAD

**Issue by yuliagrishina** [proycon/pynlpl#7]
The result of the intersection of the WordAlignment and the MultiWordAlignment does not contain the intersection of 0-0 (is always "None").  This happens because of the line 297 in the code (revalignment[0] = 0):
        `if revalignment[i] and revalignment[i] in x:`

Worked well for me with  just `if revalignment[i] in x:`

**Comment by proycon** [comment]
Thanks for the fix! I'll apply it
